Cocktail.create(name: "shitty drink")
Cocktail.create(name: "shitty alchohol")
Cocktail.create(name: "shitty mint")

Ingredient.create(name: "shitty lemon")
Ingredient.create(name: "shitty ice")
Ingredient.create(name: "shitty zest ")
Ingredient.create(name: "shitty club soda")
Ingredient.create(name: "shitty citrus wedge")
Ingredient.create(name: "shitty orange")
Ingredient.create(name: "shitty grapefruit")
Ingredient.create(name: "shitty Vodka")
Ingredient.create(name: "shitty scotch ")
Ingredient.create(name: "shitty bourbon")
Ingredient.create(name: "shitty whisky")
Ingredient.create(name: "shitty rye ")
Ingredient.create(name: "shitty Gin")
Ingredient.create(name: "shitty Rum")
Ingredient.create(name: "shitty Tequila ")
Ingredient.create(name: "shitty Coffee-flavored liqueur")
Ingredient.create(name: "shitty Amaretto")
Ingredient.create(name: "shitty Cognac")
Ingredient.create(name: "shitty Cola")
Ingredient.create(name: "shitty cherry")
Ingredient.create(name: "shitty Ginger ale")
Ingredient.create(name: "shitty ginger beer")
Ingredient.create(name: "shitty Grand Marnier")
Ingredient.create(name: "shitty Malibu rum")
